CREATE TABLE ETAPA (
    	ID_ETAPA varchar2(30) NOT NULL,
    	FECHA varchar2(20) NOT NULL,
    	RECORRIDO number(10) NOT NULL,
    	CONSTRAINT PK_ID_ETAPA PRIMARY KEY (ID_ETAPA)
);
CREATE TABLE VEHICULO(
        ID_VEHICULO varchar2 (30) NOT NULL,
        NOMBRE_EQUIPO varchar2 (30) NOT NULL,
        TIPO varchar2 (20),
        POTENCIA number (4),
        PILOTO varchar2 (30) NOT NULL,
        COPILOTO varchar2 (30),
        CLASIFICACION varchar2 (20) NOT NULL,
	TIEMPO_TOTAL varchar2 (30),
        CONSTRAINT PK_ID_VEHICULO PRIMARY KEY (ID_VEHICULO)
);
CREATE TABLE RESULTADO (
        ID_RESULTADO varchar2(30) NOT NULL,
        ID_ETAPA  varchar2(30) NOT NULL,
        ID_VEHICULO varchar2(30) NOT NULL,
    	TIEMPO VARCHAR2(30) NOT NULL,
    	CONSTRAINT PK_ID_RESULTADO PRIMARY KEY (ID_RESULTADO),
    	CONSTRAINT FK_ID_ETAPA FOREIGN KEY (ID_ETAPA) REFERENCES ETAPA(ID_ETAPA),
    	CONSTRAINT FK_ID_VEHICULO FOREIGN KEY (ID_VEHICULO)REFERENCES VEHICULO(ID_VEHICULO)

);